env:
  browser: true
  es2021: true
parserOptions:
  sourceType: module
  ecmaVersion: latest
settings:
  react:
    version: detect
plugins:
  - simple-import-sort
  - import
rules:
  simple-import-sort/imports: error
  simple-import-sort/exports: error
  import/first: error
  import/newline-after-import: error
  import/no-duplicates: error
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - prettier
